title: Jatkuvan oppimisen alusta
description: Jatkuvan oppimisen alustan demo-sivut. Sivustoa rakennetaan hankkeiden työpajoissa!
show_downloads: false
google_analytics:
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

