title: Projektien testisivusto
description: Jatkuvan oppimisen julkaisualustan demo-sivut. Testaan tällä sivustolla GitHub pages käyttöä projektien julkaisussa.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

